### PR TITLE
Update Mosquitto v2.0.12, Plugin v1.8.2

### PR DESCRIPTION
**Pull request by hebbarguru2**
Changed Dockerfile to create plugin based on newer versions of Mosquitto v2.0.12 and mosquito-go-auth v1.8.2.
Modified main.go and main_test.go to support method signatures of the new plugin.

### CODE REVIEW

**Comment by karlTGA** [comment]
Hej @hebbarguru2 ,
thank you for that contribution. But you PR seems a bit odd. At first github marks every line as new, that make the review much harder. And it seems, that you use an old version of the plugin (1.1). The current version of the plugin is 1.5 and supports client_id patterns and scopes. Please fix that and when the tests not failing, I can merge that PR.

**Comment by hebbarguru2** [comment]
Hey @karlTGA 
Thank you for your response. Yeah that's surprising, in my local machine it shows only changes. I'll check regarding this again. Maybe the way of creating pull request was wrong. 
It says v1.1, but I took the latest release code(v1.2 , in the code main.go it says version=1.1 and I didn't change it). Do you want me to build using the master branch ? 
I'll take a look at the tests as well.

**Comment by karlTGA** [comment]
Yeah, @hebbarguru2 `v1.1` is definitely old. The current version in the master is `v1.5`.
https://github.com/gewv-tu-dresden/mosquitto-go-auth-oauth2/blob/6aa307c8a955d4f49f8fc00820be597a3331460e/src/main.go#L182

If your are not sure, than sync your fork (maybe you have to add this repo as a  new remote) and sync your master with this master and then merge your changes or better implement them in a new fresh branch.

**Comment by hebbarguru2** [comment]
@karlTGA thanks, I'll work with the fork of the master branch now. 
Do you suggest , we close/cancel this pull request and delete the branch ? So that I can create a new branch in a new fork and create another new pull request with the changes as per v1.5 ?

**Comment by karlTGA** [comment]
You can try to reuse your old branch. But if you start with the wrong branch, it is maybe easier to make a fresh start and copy and paste your changes from the old branch.

**Pull request closed without merging**
